[General]
type=color
color=#eef6f0
font=Google-Sans
text=#0F3C2C
subtext0=#1E4F3E
subtext1=#8ca090
surface0=#E9F3EB
surface1=#BEE8C7
surface2=#d2ebd4
crust=#0A281D
mauve=#0F3C2C
sapphire=#BEE8C7
red=#ea1821
mantle=#D0EADB
base=#eef6f0
overlay0=#8ca090
green=#1E4F3E
